### ISSUE TITLE
Fix get_e1g2T

### ISSUE THREAD

**Issue by rmjarvis** [esheldon/ngmix#10]
The code to compute the net e1,e2 for a mixture model isn't quite right.  I believe the code for `get_e1e2T` should replace the computation of irr,irc,icc with:
```
        irr=((gm['irr'] + gm['row']**2)*gm['p']).sum()*ipsum
        irc=((gm['irc'] + gm['row']*gm['col'])*gm['p']).sum()*ipsum
        icc=((gm['icc'] + gm['col']**2)*gm['p']).sum()*ipsum
```
I think that should make the code compute the correct moments and then the correct e1,e2,T.

Making this change can only increase the value of T, but I think the effect on e1,e2 can be in any direction.  So it is possible that this explains why ngmix PSF shapes don't seem to match up with either im3shape or HSM.

**Comment by esheldon** [comment]
Should the row col be relative to the center?
```
row,col=self.get_cen()
rowdiff=gm['row']-row
coldiff=gm['col']-col

irr=((gm['irr'] + rowdiff**2)*gm['p']).sum()*ipsum
irc=((gm['irc'] + rowdiff*coldiff)*gm['p']).sum()*ipsum
icc=((gm['icc'] + coldiff**2)*gm['p']).sum()*ipsum
```

**Comment by rmjarvis** [comment]
Yes.  Sorry, I just assumed (always a mistake) that that was what the 'row', 'col' parameters were.  They should be the r,c offsets relative to the centroid.

This formula is basically just the parallel axis theorem for second moments.  I_offset = I_center + r^2.

**Comment by esheldon** [comment]
Yes, thank you, I'll implement this soon.

**Comment by beckermr** [comment]
The parallel axis theorem seems like a sledgehammer for these purposes! However, now I can say I have seen it used somewhere in real research, as opposed to before when I just needed it to solve made up mechanics problems.

**Comment by esheldon** [comment]
I remember someone (maybe Mike even) suggesting this solution to me in the past, but I quickly forgot it and didn't implement it.

I've pushed a change to master that implements this.
