### ISSUE TITLE
remove py2 support and major release 2.0

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmix#105]
End py2 support and make a new major release

Will the older 1.* releases that support py27 in conda-forge still work?

**Comment by beckermr** [comment]
Yep. Any release in conda will still work as long as the env solves. Eventually, things might get hairy, but we are not actively removing old things.

**Comment by esheldon** [comment]
I'm finished, but happy to hear more ideas for v2 prep

**Comment by beckermr** [comment]
Let's put out a release candidate and take it for a spin in places?

**Comment by esheldon** [comment]
Can you remind me what conda-forge won't pick up?  `v2.0.0rc1` ?

**Comment by beckermr** [comment]
See here: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#version-ordering

That tag should work.

**Comment by esheldon** [comment]
Is the custom to put this into the `__version__` as well, or do we leave that as `2.0.0` ?

**Comment by beckermr** [comment]
I'd put it in both

**Comment by esheldon** [comment]
I tagged `2.0.0rc1`

**Comment by esheldon** [comment]
- [ ] Update the README.md to indicate an API change
- [ ] Update CHANGES.md if needed
- [ ] Make sure wiki is up to date
