### ISSUE TITLE
rename some classes

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmix#149]
Names like `LM` are confusing

* `LM` -> `Fitter`
* `LMCoellip` -> `CoellipFitter`
* `GMixEM` -> `EMFitter`
* `GMixEMFixCen` -> `EMFitterFixCen`
* `GMixEMFluxOnly` -> `EmFitterFluxOnly`
* `TemplateFluxFitter` -> `PSFFluxFitter` (we can still support non-psf flux fitting)

**Comment by esheldon** [comment]
Pull these often used classes into the main namespace?  Add `__all__` as well

**Comment by beckermr** [comment]
`Fitter` or `LMFitter`?

**Comment by esheldon** [comment]
I think `LM` is confusing, I think few people could guess that it stands for Levenberg Marquardt and no one cares.  We don't support any other max like fitters any m ore.

On the other hand, anyone who knew what `EM` is will guess that one and use it if needed
