### ISSUE TITLE
Possible double pixel convolution in metacal images?

### ISSUE THREAD

**Issue by EiffL** [esheldon/ngmix#160]
Going over the different steps in the metacal procedure, I got a bit puzzled by this line where if I understand correctly the output images are drawn:
https://github.com/esheldon/ngmix/blob/8e81c5337b022e06c517c4abb8a7bdae7204d737/ngmix/metacal/metacal.py#L303

What puzzles me is when drawn here, the shear galaxy image should have already been reconvolved with the target PSF, which already contains the pixel response (added [here](https://github.com/esheldon/ngmix/blob/8e81c5337b022e06c517c4abb8a7bdae7204d737/ngmix/metacal/metacal.py#L252)), so I  would expect a `method="no_pixel"` when drawing this galaxy.

To make things clearer for me, I tried to do a pure GalSim equivalent, starting from the metacal example script [here](https://github.com/esheldon/ngmix/blob/master/examples/metacal/metacal.py). Given some `obs` and `obsdict` obtained by metacal, to reproduce the output with GalSim I need to do:

``` python
# Grab observations
im   = galsim.InterpolatedImage(galsim.Image(obs.image, scale=0.263))
psf  = galsim.InterpolatedImage(galsim.Image(obs.psf.image, scale=0.263))
rpsf = obsdict['noshear'].psf.galsim_obj 
# Deconvolve input image by PSF+pixel
gal = galsim.Convolve([im, galsim.Deconvolve(psf)])
# Apply shear and reconvolve by target PSF !!!which should contain the pixel response as well !!!
gal_1p = galsim.Convolve([gal.shear(g1=0.01,g2=0), rpsf])
# Draw the postage stamp
rec_1p = gal_1p.drawImage(nx=42,ny=42, scale=0.263).array
```
which gives me the following residuals when compared to `obsdict['1p'].image`:
![image](https://user-images.githubusercontent.com/861591/122815361-a4390780-d2d5-11eb-94e2-ae33edb94dfd.png)

but note that I draw the galaxy without the `method="no_pixel"` flag despite the reconvolution PSF being already pixel convolved.

Am I missing something? or is the output metacal image convolved with the pixel response twice (which doesn't matter that much probably)?

**Comment by beckermr** [comment]
Your code sample missed and extra deconv with the pixel.

**Comment by beckermr** [comment]
Woops I misread. Whether or not the reconv psf has a pixel in it is a matter of convention. I think ngmix takes the convention that it doesn't.

**Comment by beckermr** [comment]
The reconv psf is a model that is fit to the observed one and then expanded. 

All that matters is that you render it consistently with how you render the image

**Comment by esheldon** [comment]
The code in metacal is in fact reconvolving the psf by the pixel (or including it in the gauss fit etc.) so I think Francois is right, there is a double convolution.

I'm not sure when this bug crept in, it is also in 1.3.8

I verified that if I add no_pixel the tests still pass except the one that compares the response directly to values from 1.3.8

**Comment by esheldon** [comment]
This is just a small extra convolution.  I don't think this could have caused any bias.  It resulted in smaller response for galaxies.

**Comment by beckermr** [comment]
Ack. You guys are right. :/

An extra pixel seems pretty non-trivial to me given that a typical psf is only ~4 pixels at its fwhm, right?

**Comment by beckermr** [comment]
I'm pretty skeptical we could have gotten the results we have this way. 

Maybe the fitgauss version avoids the bug?

**Comment by beckermr** [comment]
@esheldon did you run the shear recovery integration tests or the unit tests?

**Comment by beckermr** [comment]
Ohhhhhh. This bug is silent because errors we make likely cancel when we divide by the response.

**Comment by esheldon** [comment]
yep

The mdet integration test won't work because we compare to 1.3.8...  Matt I think you wrote that. What do you propose?

**Comment by beckermr** [comment]
Let it fail. LSST dm is stuck on thr v 1x series. We might consider backporting and releasing 1.3.9 with this fix.

**Comment by esheldon** [comment]
yeah, backporting might be good
