### ISSUE TITLE
should we use NaN for what are currently missing data in results

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmix#175]
e.g. in moments results, values like S/N are simply missing if they are not calculated

We could ensure they are always present, put in nan.

This would simplify copying to output data structures for downstream.

fitsio has good support for nan

**Comment by beckermr** [comment]
We've been using 9999 etc. I'm ok with NaN but note that we cannot support missing int values with NaN. Not sure if we care about that.

**Comment by esheldon** [comment]
In any case, part of this issue is that some things don't have defaults.

**Comment by beckermr** [comment]
I'm ok with NaN too I think. Agreed we need to fill out all of the data each time.
