### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by beckermr** [esheldon/ngmix#25]
The minimal set of things to cover is
- [x] Jacobians
- [x] gmixes
- [x] fitting.py
- [ ] bootstrap.py (boostrappers and runners) 
- [ ] metacal full reproducibility test (requires most of above)

**Comment by beckermr** [comment]
Tests of fitting the basic models is the highest priority.

**Comment by esheldon** [comment]
there are some tests now, but nothing is actually asserted :)
