### ISSUE TITLE
model type "sersic" results in "Bad gmix model: 8"

### ISSUE THREAD

**Issue by pmelchior** [esheldon/ngmix#30]
```
import ngmix
pars_sersic = [1.5, 0.0, 0.0, 0.2, -0.1, 16.0, 100.0]
ngmix.GMixModel(pars_sersic,"sersic")
```

leads to the above ngmix error. I checked that "sersic" is in the dictionary of implemented models, hence the number 8 for the model. But apparently some of the actual implementation is missing.

Is this the right way to implement a model with a free Sersic index? Also, I needed to guess the order of the parameters, but different permutations of the order did not get rid of the error.

**Comment by esheldon** [comment]
The sersic fitting never worked very well.  I no longer support it.

It was a bad hack.  I fit gaussian mixtures to sersic profiles generated by galsim,  with different n.  Then when doing the fit with ngmix, I interpolated between these profiles to evaluate a model with particular n.  This interpolation never worked well.

**Comment by pmelchior** [comment]
Understood. Do you have a sense whether the interpolation problem could be overcome if one looked closer at it, i.e. with more testing or alternative interpolation schemes?

**Comment by esheldon** [comment]
Not sure, maybe.  I think Dustin lang also looked into it, he may have
insight
