### ISSUE TITLE
joint priors require centre prior to have nonexistent method

### ISSUE THREAD

**Issue by rlschuhmann** [esheldon/ngmix#41]
Several joint prior classes in `joint_prior.py` require the centre prior to have the method `cen_prior.get_lnprob_scalar_sep(pars[0],pars[1])`. None of the priors defined in `priors.py` have this method. This leads to crashes when executing `fill_fdiff`.

**Comment by esheldon** [comment]
actually no, there is a method called that.

Did you actually install the code?  It will compile that method in a c function

**Comment by rlschuhmann** [comment]
I installed it via `python setup.py install --user`. Is that sufficient for the c function to be 1) compiled and 2) found by python? This is my prior setup:
```
                cen_prior=ngmix.priors.CenPrior(loc0, loc1, width0, width1)
                g_prior=ngmix.priors.ZDisk2D(1.)
                T_prior=ngmix.priors.FlatPrior(0., Tmax)
                F_prior=ngmix.priors.FlatPrior(0., Fmax)
                joint_prior=ngmix.joint_prior.PriorSimpleSep(cen_prior, g_prior, T_prior, F_prior)

```

**Comment by esheldon** [comment]
I don't know what the `--user` command does.

One problem might be if you are trying to run the code from the ngmix directory; it will get confused and try to load it from there instead of the installed version

**Comment by esheldon** [comment]
In other words, cd away from that directory and try to import ngmix, does it work?

**Comment by rlschuhmann** [comment]
Now it does, yes! (`--user` allows local building/installing without root.) 
Will t
