### ISSUE TITLE
Missing abs in calculation of sdet

### ISSUE THREAD

**Issue by rmjarvis** [esheldon/ngmix#46]
The following code works correctly on v1.0.0, but fails on v1.1.0rc1.  
```
jac = ngmix.Jacobian(dudx=0, dudy=-0.2, dvdx=-0.2, dvdy=0, x=23, y=23)
assert np.allclose(jac.get_sdet(), 0.2)
```

The problem is a missing abs in the calculation of `sdet` in `Jacobian._finish_init`.  The bug was introduced when you changed the definition of `det` to no longer mean the absolute value of the determinant. 

Indeed I'm not completely sure if the latter change (which seems to be an undocumented API change in v1.0 -> v1.1) was intended or not.  But I'm quite sure that sdet should mean the sqrt(|det|) regardless.

(This bug bit Rebecca Chen recently when using ngmix to measure Piff shapes.)

**Comment by esheldon** [comment]
It is from commit 998fe6f7017b28411b00e043d86faee4764e37c3

**Comment by esheldon** [comment]
I was correcting a bug in the det calculation; I had the abs there instead of on the sqrt.

But I forgot to move the abs into the sqrt after that

**Comment by esheldon** [comment]
this has been fixed
