### ISSUE TITLE
"TypeError" when doing metacal+shape measurement with bootstrap

### ISSUE THREAD

**Issue by aguinot** [esheldon/ngmix#56]
Hello,

I tried running the metacal example (using the bootstrap solution) from the Wiki page and I got the following error on a lot of images :
```python
TypeError: __init__() missing 1 required positional argument: 'value'
```
This error seems to come from `scipy.optimize.leastsq` function..

Here are the version of the different libraries used :
python = 3.6.8
scipy = 1.2.0
ngmix = v1.2 (clone from the master branch)
galsim = 2.1.4

**Comment by esheldon** [comment]
This is due to a bug in the latest release of numba.

You can temporarily fix this by downgrading the numba version using `conda install numba=0.40`

**Comment by aguinot** [comment]
Thank you for the quick answer, this fix work for me.
I guess you can cancelled my pull request.

**Comment by esheldon** [comment]
I will leave it open for now, so others can see the temporary fix. I'll close it when the next version of numba is released (which should have a fix)
