### ISSUE TITLE
Typo in `GMixBDF` docstring?

### ISSUE THREAD

**Issue by sweverett** [esheldon/ngmix#70]
I think there may be a typo in the [docstring for `GMixBDF`](https://github.com/esheldon/ngmix/blob/v1.3.3/ngmix/gmix.py#L943). It states that the constructor parameters should be the following:
```
Parameters
----------
pars: sequence
        [c1,c2,g1,g2,T,flux]
TdByTe: number, optional
        Optionally set TdByTe.  Defaults to 1.0
```
However when I tried constructing a `GMixBDF` object this way, it fails:
```python
gmix.GMixBDF(pars=[0, 0, 0.25, 0.25, 1., 100.], TdByTe=2.)
```
```
---------------------------------------------------------------------------
GMixFatalError                            Traceback (most recent call last)
<ipython-input-4-fcf2c55ef9ea> in <module>()
----> 1 gmix.GMixBDF(pars=[0, 0, 0.25, 0.25, 1., 100.], TdByTe=2.)

/home/spencer/miniconda3/envs/balrog/lib/python2.7/site-packages/ngmix/gmix.pyc in __init__(self, pars, TdByTe)
    955 
    956         self._TdByTe = float(TdByTe)
--> 957         super(GMixBDF,self)._do_init(pars,'bdf')
    958 
    959     def copy(self):

/home/spencer/miniconda3/envs/balrog/lib/python2.7/site-packages/ngmix/gmix.pyc in _do_init(self, pars, model)
    848 
    849         self._set_fill_func()
--> 850         self.fill(pars)
    851 
    852     def copy(self):

/home/spencer/miniconda3/envs/balrog/lib/python2.7/site-packages/ngmix/gmix.pyc in fill(self, pars)
    309             err="model '%s' requires %s pars, got %s"
    310             err =err % (self._model_name,self._npars, npars)
--> 311             raise GMixFatalError(err)
    312 
    313         self._fill(pars)

GMixFatalError: "model 'bdf' requires 7 pars, got 6"
```
Presumably this is because `fracdev` was never assigned at construction time. Checking [gmix_fill_bdf](https://github.com/esheldon/ngmix/blob/v1.3.3/ngmix/gmix_nb.py#L505) it looks like the docstring should instead read:
```
Parameters
----------
pars: sequence
        [c1,c2,g1,g2,T,fracdev,flux]
TdByTe: number, optional
        Optionally set TdByTe.  Defaults to 1.0
```

**Comment by sweverett** [comment]
Is there a reason why `fracdev` is contained in `pars` for `bdf` while passed as a separate parameter for `cm`? This was a bit unintuitive.

**Comment by esheldon** [comment]
it is cm that is untuitive

in bdf fracdev is a full fledged parameter in the fitting, so it is part of the pars. In cm the fracdev is fixed.

To do the fitting we first calculated fracdev from exp and dev fits and then rand the cm fit fixing fracdev and TdByTe

anyway, happy to take a pull request

**Comment by sweverett** [comment]
Thanks for the explanation, will make a pull request now.
