### ISSUE TITLE
release 1.3.5

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmix#81]
this is needed by the balrog folks

**Comment by esheldon** [comment]
@beckermr should we release after your dev T bug fix is merged?

**Comment by beckermr** [comment]
I am not sure if this will be done before the end of the day.

**Comment by esheldon** [comment]
OK, I don't think it is needed for the balrog stuff, so I'll go ahead and release

**Comment by beckermr** [comment]
See my PR on the change log before hand!
